CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    job_title     VARCHAR(100),
    team          VARCHAR(60),
    manager_id    BIGINT REFERENCES users (id)
);

CREATE TABLE leave_types (
    code             VARCHAR(10) PRIMARY KEY,
    name             VARCHAR(40) NOT NULL,
    annual_quota     INT         NOT NULL,
    half_day_allowed BOOLEAN     NOT NULL,
    sort_order       INT         NOT NULL
);

CREATE TABLE holidays (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE        NOT NULL UNIQUE,
    name         VARCHAR(80) NOT NULL
);

CREATE TABLE leave_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (id),
    type_code       VARCHAR(10)  NOT NULL REFERENCES leave_types (code),
    from_date       DATE         NOT NULL,
    to_date         DATE         NOT NULL,
    half_day        BOOLEAN      NOT NULL DEFAULT FALSE,
    days            NUMERIC(4, 1) NOT NULL,
    reason          VARCHAR(250) NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    manager_comment VARCHAR(250),
    decided_by      BIGINT REFERENCES users (id),
    decided_at      TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_leave_dates CHECK (to_date >= from_date)
);

CREATE INDEX idx_leave_requests_user ON leave_requests (user_id);
CREATE INDEX idx_leave_requests_dates ON leave_requests (from_date, to_date);

CREATE TABLE app_settings (
    setting_key   VARCHAR(50)  PRIMARY KEY,
    setting_value VARCHAR(200) NOT NULL
);
