// Writes the backend URL into the production environment file before `ng build`.
// On Vercel, set API_URL to your backend, for example https://leavewise-api.onrender.com
import { writeFileSync } from 'node:fs';

const apiUrl = process.env.API_URL?.trim().replace(/\/+$/, '');

if (apiUrl) {
  writeFileSync(
    new URL('../src/environments/environment.ts', import.meta.url),
    `// Generated by scripts/set-env.mjs during the build.\nexport const environment = {\n  apiUrl: '${apiUrl}',\n};\n`,
  );
  console.log(`API_URL set to ${apiUrl}`);
} else {
  console.log('API_URL is not set, so the build uses http://localhost:8080');
}
